- project:
    templates:
      - nodejs6-jobs
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - refstack-tox-py27-func-mysql
        - refstack-tox-py36-func-mysql
    gate:
      jobs:
        - refstack-tox-py27-func-mysql
        - refstack-tox-py36-func-mysql

- job:
    name: refstack-tox-py27-func-mysql
    parent: openstack-tox
    description: |
      Run unit tests for an OpenStack Python project under cPython version 2.7.

      Uses tox with the ``py27-func-mysql`` environment.
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      tox_envlist: py27-func-mysql

- job:
    name: refstack-tox-py36-func-mysql
    parent: openstack-tox
    description: |
      Run unit tests for an OpenStack Python project under cPython version 3.6.

      Uses tox with the ``py36-func-mysql`` environment.
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      tox_envlist: py36-func-mysql
