"""added config to test table

Revision ID: 16345354480e
Revises: 53fcc008b313
Create Date: 2013-09-20 11:08:56.790834

"""

# revision identifiers, used by Alembic.
revision = '16345354480e'
down_revision = '53fcc008b313'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('config', sa.String(length=4096), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'config')
    
    ### end Alembic commands ###
