"""Adding Cloud and User models

Revision ID: 23f82f78731b
Revises: 40d4c6d389ec
Create Date: 2013-07-02 15:02:46.951119

"""

# revision identifiers, used by Alembic.
revision = '23f82f78731b'
down_revision = '40d4c6d389ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    
    ### end Alembic commands ###
