"""added email_verfied column

Revision ID: 2bad1445cf30
Revises: 16345354480e
Create Date: 2013-09-20 12:01:59.881027

"""

# revision identifiers, used by Alembic.
revision = '2bad1445cf30'
down_revision = '16345354480e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(create_constraint=False), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    ### end Alembic commands ###
