"""added architecture to cloud

Revision ID: 2d1f3e3cd357
Revises: 4a425a7aff50
Create Date: 2014-03-07 12:11:20.403933

"""

# revision identifiers, used by Alembic.
revision = '2d1f3e3cd357'
down_revision = '4a425a7aff50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cloud',
        sa.Column('architecture', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud', 'architecture')
    ### end Alembic commands ###
