"""added user - cloud relationship

Revision ID: 4288db006e5
Revises: 1d6540fc6279
Create Date: 2013-10-31 21:00:27.473833

"""

# revision identifiers, used by Alembic.
revision = '4288db006e5'
down_revision = '1d6540fc6279'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
