"""really added user - cloud relationship

Revision ID: 4f6f77184d45
Revises: 4288db006e5
Create Date: 2013-10-31 21:09:16.469966

"""

# revision identifiers, used by Alembic.
revision = '4f6f77184d45'
down_revision = '4288db006e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud', 'user_id')
    ### end Alembic commands ###
