"""added su field to user

Revision ID: 5a5148d89f90
Revises: 2bad1445cf30
Create Date: 2013-10-30 01:39:37.546697

"""

# revision identifiers, used by Alembic.
revision = '5a5148d89f90'
down_revision = '2bad1445cf30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('su', sa.Boolean()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'su')
